"""PackyCode aws-q 分组模型配置 —— Claude adaptive 模式。"""
from core.text_engine import AWSQPackyCodeText

AWSQ_MODELS = {
    # 不稳定！！！
    # 疑似审核过滤，不输出内容
    # ⚠️ claude-opus-4-8 (PackyCode) 流式调用失败 (尝试 1/5): InternalServerError("Error code: 524 - {'type': 'https://developers.cloudflare.com/support/troubleshooting/http-status-codes/cloudflare-5xx-errors/error-524/', 'title': 'Error 524: A timeout occurred', 'status': 524, 'detail': 'The origin web server did not return a complete response within the 120-second Proxy Read Timeout window. The connection was established, but the origin took too long to respond.', 'instance': 'a0424998e8bbe170', 'error_code': 524, 'error_name': 'origin_response_timeout', 'error_category': 'origin', 'ray_id': 'a0424998e8bbe170', 'timestamp': '2026-05-31T01:45:29Z', 'zone': 'www.packyapi.com', 'cloudflare_error': True, 'retryable': True, 'retry_after': 120, 'owner_action_required': True, 'what_you_should_do': '**Wait and retry.** Back off for at least 120 seconds. If the error persists, the website operator should check for long-running processes or an overloaded origin.', 'footer': 'This error was generated by Cloudflare on behalf of the website owner.'}")
    "packy-aws-q-claude-opus-4-8-nothink": (AWSQPackyCodeText, {# ⚠️ claude-opus-4-8 (PackyCode) 流式调用失败 (尝试 1/5): InternalServerError("Error code: 524 - {'type': 'https://developers.cloudflare.com/support/troubleshooting/http-status-codes/cloudflare-5xx-errors/error-524/', 'title': 'Error 524: A timeout occurred', 'status': 524, 'detail': 'The origin web server did not return a complete response within the 120-second Proxy Read Timeout window. The connection was established, but the origin took too long to respond.', 'instance': 'a0424998e8bbe170', 'error_code': 524, 'error_name': 'origin_response_timeout', 'error_category': 'origin', 'ray_id': 'a0424998e8bbe170', 'timestamp': '2026-05-31T01:45:29Z', 'zone': 'www.packyapi.com', 'cloudflare_error': True, 'retryable': True, 'retry_after': 120, 'owner_action_required': True, 'what_you_should_do': '**Wait and retry.** Back off for at least 120 seconds. If the error persists, the website operator should check for long-running processes or an overloaded origin.', 'footer': 'This error was generated by Cloudflare on behalf of the website owner.'}")
        "model_name": "claude-opus-4-8",     "group": "aws-q",
        "enable_thinking": False,
    }),
    "packy-aws-q-claude-opus-4-8-adaptive-low": (AWSQPackyCodeText, {
        "model_name": "claude-opus-4-8",     "group": "aws-q",
        "thinking_effort": "low",
    }),
    "packy-aws-q-claude-opus-4-8-adaptive-medium": (AWSQPackyCodeText, {
        "model_name": "claude-opus-4-8",     "group": "aws-q",
        "thinking_effort": "medium",
    }),
    "packy-aws-q-claude-opus-4-8-adaptive-high": (AWSQPackyCodeText, {
        "model_name": "claude-opus-4-8",     "group": "aws-q",
        "thinking_effort": "high",
    }),
    "packy-aws-q-claude-sonnet-4-6-nothink": (AWSQPackyCodeText, { # 疑似审核过滤，不输出内容
        "model_name": "claude-sonnet-4-6",   "group": "aws-q",
        "enable_thinking": False,
    }),
    "packy-aws-q-claude-sonnet-4-6-adaptive-low": (AWSQPackyCodeText, {
        "model_name": "claude-sonnet-4-6",   "group": "aws-q",
        "thinking_effort": "low",
    }),
}
